#!/bin/bash
### BEGIN INIT INFO
# Provides:          bookworm-catalog-etl
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop bookworm-catalog-etl
### END INIT INFO
# chkconfig: 35 92 1

## Include some script files in order to set and export environmental variables
## as well as add the appropriate executables to $PATH.
[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh

BOOKWORM_USER=${BOOKWORM_USER:-wbh}
BOOKWORM_HOME=/home/${BOOKWORM_USER}/${project.artifactId}-${project.version}
export BOOKWORM_HOME
CAMEL_ENCRYPTION_ALGORITHM=PBEWithMD5AndTripleDES
export CAMEL_ENCRYPTION_ALGORITHM
CAMEL_ENCRYPTION_PASSWORD=askjf0984673hjgfjhgfgj3sdflhsdf1245
export CAMEL_ENCRYPTION_PASSWORD

case "$1" in
    start)
        echo "Starting ${project.artifactId}..."
        JAVA_OPTS="-D'openjpa.ManagedRuntime=invocation(TransactionManagerMethod=com.atomikos.icatch.jta.TransactionManagerImp.getTransactionManager)'"
        JAR=${project.artifactId}-${project.version}.jar
        LOG="2>/var/log/${project.artifactId}.log 1>&2"
        sudo -Eu ${BOOKWORM_USER} sh -c "cd ${BOOKWORM_HOME} ; java ${JAVA_OPTS} -jar ${JAR} ${LOG} &"
    ;;
    stop)
        echo "Stopping ${project.artifactId}..."
        pid=$(ps ax | grep ${project.artifactId} | grep -v grep | awk '{print $1}')
        kill ${pid}
    ;;
    encrypt)
        echo "*"
        echo "* WARNING"
        echo "*"
        echo "* YOU ARE ABOUT TO CHANGE ENCRYPTION OF IMPORTANT CONFIGURATION VALUES."
        echo "* THIS MAY BREAK EXISTING PREVIOUSLY ENCRYPTED VALUES AND MAY HARM YOUR SYSTEM."
        echo "*"
        echo "* PROCEED ONLY IF YOU ARE CERTAIN ABOUT WHAT YOU'RE DOING!"
        echo "*"
        read -p "* Go ahead (y/n)?" goahead
        if [ "${goahead}" = "y" ]
        then
            declare -A pvalue
            encrypted_properties=$(grep ENC ${BOOKWORM_HOME}/conf/etl.properties)
            for ep in ${encrypted_properties}
            do
                pname=${ep%=*}
                read -p "Enter value for ${pname}: " ${pvalue[pname]}
            done
            for k in ${!pvalue[@]}
            do
                pushd ${BOOKWORM_HOME}/lib 2>/dev/null
                encrypted_value=$(java -jar camel-jasypt-2.15.1.jar -c encrypt -p ${CAMEL_ENCRYPTION_PASSWORD} -a ${CAMEL_ENCRYPTION_ALGORITHM} -i ${pvalue[$k]})
                echo "${k}=ENC(${encrypted_value})"
                popd 2>/dev/null
            done
        fi
    ;;
    *)
        echo "Usage: $0 { start | stop }"
        exit 1
    ;;
esac

exit 0
