#!/bin/bash
### BEGIN INIT INFO
# Provides:          bookworm-import
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop bookworm-import
### END INIT INFO
# chkconfig: 35 92 1

## Include some script files in order to set and export environmental variables
## as well as add the appropriate executables to $PATH.
[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh

BOOKWORM_USER=${BOOKWORM_USER:-wbh}
BOOKWORM_HOME=/home/${BOOKWORM_USER}/${project.artifactId}-${project.version}

CAMEL_ENCRYPTION_ALGORITHM=PBEWithMD5AndTripleDES
export CAMEL_ENCRYPTION_ALGORITHM
CAMEL_ENCRYPTION_PASSWORD=askjf0984673hjgfjhgfgj3sdflhsdf1245
export CAMEL_ENCRYPTION_PASSWORD

case "$1" in
    start)
        echo "Starting bookworm-datimport..."
        cd $BOOKWORM_HOME
        sudo -u ${BOOKWORM_USER} java -jar ${project.artifactId}-${project.version}.jar 2>/var/log/bookworm-datimport.log 1>&2 &
    ;;
    stop)
        echo "Stopping bookworm-datimport..."
        sudo -u ${BOOKWORM_USER}
    ;;
    encrypt)
        pushd ${BOOKWORM_HOME}/lib 2>/dev/null
        java -jar camel-jasypt-2.15.1.jar -c encrypt -p ${CAMEL_ENCRYPTION_PASSWORD} -a ${CAMEL_ENCRYPTION_ALGORITHM} -i $1
        popd 2>/dev/null
    ;;
    *)
        echo "Usage: $0 { start | stop }"; exit 1;
    ;;
esac

exit 0
